/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class MainMenu extends javax.swing.JFrame {

    private final int adminId;
    private final String adminName;

    /**
     * Creates new form mainMenu
     * @param adminId
     * @param adminName
     */
    public MainMenu(int adminId, String adminName) {
        initComponents();
        this.adminId=adminId;
        this.adminName=adminName;
        lblTextHello.setText("Hello "+adminName+ " What would you like to do?");
    }

    private MainMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextMainMenu = new javax.swing.JLabel();
        lblTextHello = new javax.swing.JLabel();
        btnConsultContacts = new javax.swing.JButton();
        btnConsultOne = new javax.swing.JButton();
        btnUpdateContact = new javax.swing.JButton();
        btnInsertContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        fondo_mainMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextMainMenu.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        lblTextMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblTextMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextMainMenu.setText("Main Menu");
        getContentPane().add(lblTextMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, 29));

        lblTextHello.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        lblTextHello.setForeground(new java.awt.Color(255, 255, 255));
        lblTextHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextHello.setText("Hello. What would you like to do?");
        getContentPane().add(lblTextHello, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 393, -1));

        btnConsultContacts.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultContacts.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnConsultContacts.setText("Consult all contacts");
        btnConsultContacts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnConsultContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultContactsActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 140, 30));

        btnConsultOne.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultOne.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnConsultOne.setText("Consult one contact");
        btnConsultOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnConsultOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultOneActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 110, 140, 30));

        btnUpdateContact.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnUpdateContact.setText("Update contact");
        btnUpdateContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        btnInsertContact.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnInsertContact.setText("Add contact");
        btnInsertContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnInsertContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        btnDeleteContact.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteContact.setText("Delete contact");
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 128, -1));

        btnLogout.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnLogout.setText("Log out ");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 186, -1, -1));

        fondo_mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_lindo.jpg"))); // NOI18N
        fondo_mainMenu.setText("jLabel1");
        getContentPane().add(fondo_mainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultContactsActionPerformed
        SelectAll newFrame=new SelectAll(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultContactsActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        Delete newFrame=new Delete(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteContactActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        Main newFrame = new Main();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInsertContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContactActionPerformed
        Insert newFrame=new Insert(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertContactActionPerformed

    private void btnUpdateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateContactActionPerformed
        Update newFrame=new Update(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateContactActionPerformed

    private void btnConsultOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultOneActionPerformed
        SelectOne newFrame=new SelectOne(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultContacts;
    private javax.swing.JButton btnConsultOne;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnInsertContact;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateContact;
    private javax.swing.JLabel fondo_mainMenu;
    private javax.swing.JLabel lblTextHello;
    private javax.swing.JLabel lblTextMainMenu;
    // End of variables declaration//GEN-END:variables
}
